CREATE PROCEDURE `Inserts` ()
BEGIN
-- Datos realistas para modelo agroexportador (15 registros por tabla)

INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('PAL-HASS', 'Palta', 'Frutas', 'Hass', 1850);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('MAN-KENT', 'Mango', 'Frutas', 'Kent', 1450);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('ARA-BLU', 'Arándano', 'Frutas', 'Biloxi', 4200);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('UVA-RG', 'Uva', 'Frutas', 'Red Globe', 2300);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('UVA-AT', 'Uva', 'Frutas', 'Autumn Crisp', 2600);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('ESP-VER', 'Espárrago', 'Hortalizas', 'Verde', 2800);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('ALC-COR', 'Alcachofa', 'Hortalizas', 'Corazón', 1900);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('QUI-BLA', 'Quinua', 'Granos', 'Blanca', 1200);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('QUI-ROJ', 'Quinua', 'Granos', 'Roja', 1350);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('CAF-ORG', 'Café', 'Procesados', 'Orgánico', 3100);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('PAL-GUA', 'Guacamole', 'Procesados', 'Premium', 3500);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('MAN-PUL', 'Pulpa de Mango', 'Procesados', 'Kent', 2100);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('ARA-CON', 'Arándano Congelado', 'Procesados', 'Biloxi', 3900);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('MAI-AM', 'Maíz', 'Granos', 'Amarillo', 900);
INSERT INTO Productos (sku,nombre_producto,categoria,variedad,precio_sugerido_exportacion) VALUES ('PAL-HAS2', 'Palta', 'Frutas', 'Hass Export', 1950);
INSERT INTO Certificaciones(nombre) VALUES('GlobalGAP');
INSERT INTO Certificaciones(nombre) VALUES('Organic');
INSERT INTO Certificaciones(nombre) VALUES('RainForest');
INSERT INTO Certificaciones(nombre) VALUES('Fair Trade');
INSERT INTO Certificaciones(nombre) VALUES('HACCP');
INSERT INTO Certificaciones(nombre) VALUES('BRC');
INSERT INTO Certificaciones(nombre) VALUES('ISO 22000');
INSERT INTO Certificaciones(nombre) VALUES('SMETA');
INSERT INTO Certificaciones(nombre) VALUES('GRASP');
INSERT INTO Certificaciones(nombre) VALUES('USDA Organic');
INSERT INTO Certificaciones(nombre) VALUES('EU Organic');
INSERT INTO Certificaciones(nombre) VALUES('PrimusGFS');
INSERT INTO Certificaciones(nombre) VALUES('IFS Food');
INSERT INTO Certificaciones(nombre) VALUES('Sedex');
INSERT INTO Certificaciones(nombre) VALUES('Carbon Neutral');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-001','2026-03-01','Fundo Camposol 1',NULL,'Verde');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-002','2026-03-02','Fundo Camposol 2',NULL,'En proceso');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-003','2026-03-03','Fundo Camposol 3',NULL,'Listo');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-004','2026-03-04','Fundo Camposol 4',NULL,'Pasado');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-005','2026-03-05','Fundo Camposol 5',NULL,'Verde');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-006','2026-03-06','Fundo Camposol 6',NULL,'En proceso');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-007','2026-03-07','Fundo Camposol 7',NULL,'Listo');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-008','2026-03-08','Fundo Camposol 8',NULL,'Pasado');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-009','2026-03-09','Fundo Camposol 9',NULL,'Verde');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-010','2026-03-10','Fundo Camposol 10',NULL,'En proceso');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-011','2026-03-11','Fundo Camposol 11',NULL,'Listo');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-012','2026-03-12','Fundo Camposol 12',NULL,'Pasado');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-013','2026-03-13','Fundo Camposol 13',NULL,'Verde');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-014','2026-03-14','Fundo Camposol 14',NULL,'En proceso');
INSERT INTO Lotes(codigo_trazabilidad,fecha_cosecha,finca_origen,certificaciones,estado_maduracion) VALUES('QR-LOT-015','2026-03-15','Fundo Camposol 15',NULL,'Listo');
INSERT INTO LoteCertificaciones VALUES(1,1);
INSERT INTO LoteCertificaciones VALUES(1,2);
INSERT INTO LoteCertificaciones VALUES(2,2);
INSERT INTO LoteCertificaciones VALUES(2,3);
INSERT INTO LoteCertificaciones VALUES(3,3);
INSERT INTO LoteCertificaciones VALUES(3,4);
INSERT INTO LoteCertificaciones VALUES(4,4);
INSERT INTO LoteCertificaciones VALUES(4,5);
INSERT INTO LoteCertificaciones VALUES(5,5);
INSERT INTO LoteCertificaciones VALUES(5,6);
INSERT INTO LoteCertificaciones VALUES(6,6);
INSERT INTO LoteCertificaciones VALUES(6,7);
INSERT INTO LoteCertificaciones VALUES(7,7);
INSERT INTO LoteCertificaciones VALUES(7,8);
INSERT INTO LoteCertificaciones VALUES(8,8);
INSERT INTO LoteCertificaciones VALUES(8,9);
INSERT INTO LoteCertificaciones VALUES(9,9);
INSERT INTO LoteCertificaciones VALUES(9,10);
INSERT INTO LoteCertificaciones VALUES(10,10);
INSERT INTO LoteCertificaciones VALUES(10,11);
INSERT INTO LoteCertificaciones VALUES(11,11);
INSERT INTO LoteCertificaciones VALUES(11,12);
INSERT INTO LoteCertificaciones VALUES(12,12);
INSERT INTO LoteCertificaciones VALUES(12,13);
INSERT INTO LoteCertificaciones VALUES(13,13);
INSERT INTO LoteCertificaciones VALUES(13,14);
INSERT INTO LoteCertificaciones VALUES(14,14);
INSERT INTO LoteCertificaciones VALUES(14,15);
INSERT INTO LoteCertificaciones VALUES(15,15);
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 1','Distribuidor','Estados Unidos','contacto1@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 2','Retailer','Paises Bajos','contacto2@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 3','Broker','España','contacto3@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 4','Procesadora','China','contacto4@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 5','Distribuidor','Chile','contacto5@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 6','Retailer','Canadá','contacto6@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 7','Broker','Alemania','contacto7@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 8','Procesadora','Francia','contacto8@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 9','Distribuidor','Italia','contacto9@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 10','Retailer','Reino Unido','contacto10@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 11','Broker','Corea del Sur','contacto11@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 12','Procesadora','Japón','contacto12@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 13','Distribuidor','México','contacto13@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 14','Retailer','Brasil','contacto14@agropartner.com');
INSERT INTO Canales(nombre_empresa,tipo_canal,pais_destino,email_contacto) VALUES('AgroPartner 15','Broker','Australia','contacto15@agropartner.com');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-001',1,'EXW','USD',16200,'Pendiente');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-002',2,'FOB','USD',17400,'Pagado');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-003',3,'CIF','USD',18600,'Vencido');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-004',4,'DDP','USD',19800,'Pendiente');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-005',5,'EXW','USD',21000,'Pagado');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-006',6,'FOB','USD',22200,'Vencido');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-007',7,'CIF','USD',23400,'Pendiente');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-008',8,'DDP','USD',24600,'Pagado');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-009',9,'EXW','USD',25800,'Vencido');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-010',10,'FOB','USD',27000,'Pendiente');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-011',11,'CIF','USD',28200,'Pagado');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-012',12,'DDP','USD',29400,'Vencido');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-013',13,'EXW','USD',30600,'Pendiente');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-014',14,'FOB','USD',31800,'Pagado');
INSERT INTO Transacciones(factura_nro,canal_id,incoterm,moneda,monto_total,estado_pago) VALUES('FAC-2026-015',15,'CIF','USD',33000,'Vencido');
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(1,1,1,10.800,1050.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(2,2,2,11.600,1100.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(3,3,3,12.400,1150.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(4,4,4,13.200,1200.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(5,5,5,14.000,1250.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(6,6,6,14.800,1300.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(7,7,7,15.600,1350.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(8,8,8,16.400,1400.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(9,9,9,17.200,1450.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(10,10,10,18.000,1500.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(11,11,11,18.800,1550.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(12,12,12,19.600,1600.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(13,13,13,20.400,1650.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(14,14,14,21.200,1700.00);
INSERT INTO TransaccionesDetalle(transaccion_id,producto_id,lote_id,cantidad_tm,precio_unitario_tm) VALUES(15,15,15,22.000,1750.00);
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(1,'MSCU000001','ABC-201',5.00,'Puerto del Callao','2026-07-01 08:00:00','Incompleto');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(2,'MSCU000002','ABC-202',5.00,'Puerto del Callao','2026-07-02 08:00:00','En Revisión');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(3,'MSCU000003','ABC-203',5.00,'Puerto del Callao','2026-07-03 08:00:00','Aprobado/Liberado');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(4,'MSCU000004','ABC-204',5.00,'Puerto del Callao','2026-07-04 08:00:00','Incompleto');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(5,'MSCU000005','ABC-205',5.00,'Puerto del Callao','2026-07-05 08:00:00','En Revisión');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(6,'MSCU000006','ABC-206',5.00,'Puerto del Callao','2026-07-06 08:00:00','Aprobado/Liberado');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(7,'MSCU000007','ABC-207',5.00,'Puerto del Callao','2026-07-07 08:00:00','Incompleto');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(8,'MSCU000008','ABC-208',5.00,'Puerto del Callao','2026-07-08 08:00:00','En Revisión');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(9,'MSCU000009','ABC-209',5.00,'Puerto del Callao','2026-07-09 08:00:00','Aprobado/Liberado');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(10,'MSCU000010','ABC-210',5.00,'Puerto del Callao','2026-07-10 08:00:00','Incompleto');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(11,'MSCU000011','ABC-211',5.00,'Puerto del Callao','2026-07-11 08:00:00','En Revisión');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(12,'MSCU000012','ABC-212',5.00,'Puerto del Callao','2026-07-12 08:00:00','Aprobado/Liberado');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(13,'MSCU000013','ABC-213',5.00,'Puerto del Callao','2026-07-13 08:00:00','Incompleto');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(14,'MSCU000014','ABC-214',5.00,'Puerto del Callao','2026-07-14 08:00:00','En Revisión');
INSERT INTO Despachos(transaccion_id,contenedor_id,placa_camion,temp_requerida_celsius,puerto_origen,eta_puerto,estatus_documental) VALUES(15,'MSCU000015','ABC-215',5.00,'Puerto del Callao','2026-07-15 08:00:00','Aprobado/Liberado');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(1,'2026-07-01 06:00:00','2026-07-01 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(2,'2026-07-02 06:00:00','2026-07-02 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(3,'2026-07-03 06:00:00','2026-07-03 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(4,'2026-07-04 06:00:00','2026-07-04 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(5,'2026-07-05 06:00:00','2026-07-05 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(6,'2026-07-06 06:00:00','2026-07-06 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(7,'2026-07-07 06:00:00','2026-07-07 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(8,'2026-07-08 06:00:00','2026-07-08 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(9,'2026-07-09 06:00:00','2026-07-09 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(10,'2026-07-10 06:00:00','2026-07-10 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(11,'2026-07-11 06:00:00','2026-07-11 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(12,'2026-07-12 06:00:00','2026-07-12 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(13,'2026-07-13 06:00:00','2026-07-13 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(14,'2026-07-14 06:00:00','2026-07-14 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO MonitoreoPuerto(despacho_id,hora_llegada_real,hora_inicio_carga,tiempo_espera_horas,motivo_demora) VALUES(15,'2026-07-15 06:00:00','2026-07-15 08:00:00',2.00,'Inspección sanitaria');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente1@mail.com','Cliente 1','Estados Unidos','Salud/Nutricion');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente2@mail.com','Cliente 2','Paises Bajos','Sostenibilidad');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente3@mail.com','Cliente 3','España','Recetas/Gourmet');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente4@mail.com','Cliente 4','China','Salud/Nutricion');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente5@mail.com','Cliente 5','Chile','Sostenibilidad');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente6@mail.com','Cliente 6','Canadá','Recetas/Gourmet');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente7@mail.com','Cliente 7','Alemania','Salud/Nutricion');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente8@mail.com','Cliente 8','Francia','Sostenibilidad');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente9@mail.com','Cliente 9','Italia','Recetas/Gourmet');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente10@mail.com','Cliente 10','Reino Unido','Salud/Nutricion');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente11@mail.com','Cliente 11','Corea del Sur','Sostenibilidad');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente12@mail.com','Cliente 12','Japón','Recetas/Gourmet');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente13@mail.com','Cliente 13','México','Salud/Nutricion');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente14@mail.com','Cliente 14','Brasil','Sostenibilidad');
INSERT INTO ConsumidoresFinales(email,nombre,pais_residencia,interes_principal) VALUES('cliente15@mail.com','Cliente 15','Australia','Recetas/Gourmet');
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(1,1,'2026-08-01 14:00:00','Excelente calidad y frescura',2);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(2,2,'2026-08-02 14:00:00','Excelente calidad y frescura',3);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(3,3,'2026-08-03 14:00:00','Excelente calidad y frescura',4);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(4,4,'2026-08-04 14:00:00','Excelente calidad y frescura',5);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(5,5,'2026-08-05 14:00:00','Excelente calidad y frescura',1);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(6,6,'2026-08-06 14:00:00','Excelente calidad y frescura',2);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(7,7,'2026-08-07 14:00:00','Excelente calidad y frescura',3);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(8,8,'2026-08-08 14:00:00','Excelente calidad y frescura',4);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(9,9,'2026-08-09 14:00:00','Excelente calidad y frescura',5);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(10,10,'2026-08-10 14:00:00','Excelente calidad y frescura',1);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(11,11,'2026-08-11 14:00:00','Excelente calidad y frescura',2);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(12,12,'2026-08-12 14:00:00','Excelente calidad y frescura',3);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(13,13,'2026-08-13 14:00:00','Excelente calidad y frescura',4);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(14,14,'2026-08-14 14:00:00','Excelente calidad y frescura',5);
INSERT INTO InteraccionesQR(consumidor_id,lote_id,fecha_escaneo,comentario_calidad,puntuacion_sabor) VALUES(15,15,'2026-08-15 14:00:00','Excelente calidad y frescura',1);
END